version: "3.9"

services:

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306" # útil para conectarte con MySQL Workbench/DBeaver en local; puedes quitarlo en prod
    volumes:
      - db_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d # otorga permisos al usuario la primera vez que arranca
    networks:
      - backend-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  back-despacho:
    build:
      context: ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
    container_name: back-despacho
    restart: unless-stopped
    environment:
      DB_ENDPOINT: mysql
      DB_PORT: 3306
      DB_NAME: despacho_db
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8081:8081" # tu app escucha en 8081 (server.port=8081)
    networks:
      - backend-net

  back-ventas:
    build:
      context: ./back-Ventas_SpringBoot/Springboot-API-REST
    container_name: back-ventas
    restart: unless-stopped
    environment:
      DB_ENDPOINT: mysql
      DB_PORT: 3306
      DB_NAME: ventas_db
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080" # tu app escucha en el 8080 por defecto
    networks:
      - backend-net

  front:
    build:
      context: ./front_despacho
    container_name: front-despacho
    restart: unless-stopped
    depends_on:
      - back-despacho
      - back-ventas
    ports:
      - "80:80"
    networks:
      - backend-net

volumes:
  db_data:

networks:
  backend-net:
    driver: bridge
