name: Desplegar Backend Ventas a Amazon ECR

on:
  push:
    branches: [ "main" ]
    paths:
      - 'back-Ventas_SpringBoot/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Configurar credenciales de AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Iniciar sesión en Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Construir y subir imagen
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: app-back-ventas
        IMAGE_TAG: latest
      run: |
        cd back-Ventas_SpringBoot/Springboot-API-REST
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Forzar nuevo despliegue en ECS
      run: |
        aws ecs update-service \
          --cluster cluster-devops-HDJ \
          --service svc-ventas \
          --force-new-deployment \
          --region us-east-1
